global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@bdc.com'
  smtp_auth_username: 'alertmanager@bdc.com'
  smtp_auth_password: 'password'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'email-notifications'
  routes:
  - match:
      severity: critical
    receiver: 'email-notifications'
    repeat_interval: 1h
  - match:
      severity: warning
    receiver: 'email-notifications'
    repeat_interval: 12h

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'admin@bdc.com'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname']