services:
  test-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.test-api
    container_name: bdc_test_api
    restart: unless-stopped
    ports:
      - "8888:8888"
    networks:
      - bdc_network

  test-interface:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.html
    container_name: bdc_interface
    restart: unless-stopped
    ports:
      - "8091:80"
    networks:
      - bdc_network
    depends_on:
      - test-api

networks:
  bdc_network:
    driver: bridge