server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*))\|
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          stream:
          container_name:
      - output:
          source: output

  # BDC specific logs
  - job_name: bdc-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: bdc-backend
          __path__: /var/lib/docker/containers/*bdc-backend*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
          source: output
      - labels:
          level:
      - timestamp:
          format: "2006-01-02T15:04:05.000Z"
          source: timestamp
      - output:
          source: message

  - job_name: bdc-frontend
    static_configs:
      - targets:
          - localhost
        labels:
          job: bdc-frontend
          __path__: /var/lib/docker/containers/*bdc-frontend*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
      - output:
          source: output

  - job_name: bdc-postgres
    static_configs:
      - targets:
          - localhost
        labels:
          job: bdc-postgres
          __path__: /var/lib/docker/containers/*bdc-postgres*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
      - regex:
          expression: '.*\[(?P<level>\w+)\].*'
          source: output
      - labels:
          level:
      - output:
          source: output

  - job_name: bdc-redis
    static_configs:
      - targets:
          - localhost
        labels:
          job: bdc-redis
          __path__: /var/lib/docker/containers/*bdc-redis*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
      - output:
          source: output