# AlertManager configuration for BDC application

global:
  smtp_smarthost: '${SMTP_SMARTHOST:-localhost:587}'
  smtp_from: '${SMTP_FROM:-alerts@bdc.com}'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

# Grouping and routing configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    # Critical alerts - immediate notification
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m
      
    # Warning alerts - grouped notifications
    - match:
        severity: warning
      receiver: 'warning-alerts'
      group_wait: 30s
      repeat_interval: 30m
      
    # Info alerts - daily digest
    - match:
        severity: info
      receiver: 'info-alerts'
      group_wait: 5m
      repeat_interval: 24h

    # Database specific alerts
    - match:
        service: postgres
      receiver: 'database-alerts'
      
    # Application specific alerts
    - match:
        service: bdc-backend
      receiver: 'application-alerts'

# Inhibition rules to suppress redundant alerts
inhibit_rules:
  # Suppress warning alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
    
  # Suppress individual service alerts when the whole service is down
  - source_match:
      alertname: 'ServiceDown'
    target_match_re:
      service: '.*'
    equal: ['instance']

# Notification receivers
receivers:
  # Default receiver
  - name: 'default-receiver'
    email_configs:
      - to: '${ALERT_EMAIL_DEFAULT:-admin@bdc.com}'
        subject: '[BDC] Alert: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}: {{ .Value }} {{ end }}
          {{ end }}
        html: |
          <h2>BDC Alert Notification</h2>
          {{ range .Alerts }}
          <div style="border: 1px solid #ccc; margin: 10px; padding: 10px;">
            <h3 style="color: {{ if eq .Labels.severity "critical" }}red{{ else if eq .Labels.severity "warning" }}orange{{ else }}blue{{ end }};">
              {{ .Annotations.summary }}
            </h3>
            <p><strong>Description:</strong> {{ .Annotations.description }}</p>
            <p><strong>Service:</strong> {{ .Labels.service }}</p>
            <p><strong>Time:</strong> {{ .StartsAt }}</p>
            <p><strong>Labels:</strong> {{ range .Labels.SortedPairs }}{{ .Name }}: {{ .Value }} {{ end }}</p>
          </div>
          {{ end }}

  # Critical alerts - immediate notification via multiple channels
  - name: 'critical-alerts'
    email_configs:
      - to: '${ALERT_EMAIL_CRITICAL:-admin@bdc.com,ops@bdc.com}'
        subject: '[BDC CRITICAL] {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Time: {{ .StartsAt }}
          {{ end }}
          
          Please investigate immediately!
    # Add Slack webhook for critical alerts
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#bdc-alerts-critical'
        title: '🚨 BDC Critical Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          {{ end }}
        color: 'danger'

  # Warning alerts
  - name: 'warning-alerts'
    email_configs:
      - to: '${ALERT_EMAIL_WARNING:-ops@bdc.com}'
        subject: '[BDC WARNING] {{ .GroupLabels.alertname }}'
        body: |
          ⚠️ WARNING ALERT ⚠️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Time: {{ .StartsAt }}
          {{ end }}

  # Info alerts - daily digest
  - name: 'info-alerts'
    email_configs:
      - to: '${ALERT_EMAIL_INFO:-monitoring@bdc.com}'
        subject: '[BDC INFO] Daily Alert Digest'
        body: |
          📊 Daily Alert Digest
          
          {{ range .Alerts }}
          - {{ .Annotations.summary }}
          {{ end }}

  # Database specific alerts
  - name: 'database-alerts'
    email_configs:
      - to: '${ALERT_EMAIL_DATABASE:-dba@bdc.com,ops@bdc.com}'
        subject: '[BDC DATABASE] {{ .GroupLabels.alertname }}'
        body: |
          🗄️ DATABASE ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Time: {{ .StartsAt }}
          {{ end }}

  # Application specific alerts
  - name: 'application-alerts'
    email_configs:
      - to: '${ALERT_EMAIL_APPLICATION:-dev@bdc.com,ops@bdc.com}'
        subject: '[BDC APPLICATION] {{ .GroupLabels.alertname }}'
        body: |
          🏗️ APPLICATION ALERT
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Time: {{ .StartsAt }}
          {{ end }}

# Templates for custom formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'