# BDC Application Alert Rules

groups:
  - name: bdc-application-alerts
    rules:
      # High error rate alerts
      - alert: HighErrorRate
        expr: rate(flask_http_request_exceptions_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          service: bdc-backend
        annotations:
          summary: "High error rate detected on BDC backend"
          description: "Error rate is {{ $value }} errors per second for the last 5 minutes"

      # High response time alerts
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(flask_http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: bdc-backend
        annotations:
          summary: "High response time detected on BDC backend"
          description: "95th percentile response time is {{ $value }} seconds"

      # Database connection alerts
      - alert: DatabaseConnectionHigh
        expr: postgresql_connections_active / postgresql_connections_max > 0.8
        for: 2m
        labels:
          severity: warning
          service: postgres
        annotations:
          summary: "High database connection usage"
          description: "Database connection usage is at {{ $value | humanizePercentage }}"

      # Memory usage alerts
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      # Disk space alerts
      - alert: LowDiskSpace
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) > 0.85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "Low disk space detected"
          description: "Disk usage is {{ $value | humanizePercentage }}"

      # Redis connection alerts
      - alert: RedisConnectionHigh
        expr: redis_connected_clients > 100
        for: 2m
        labels:
          severity: warning
          service: redis
        annotations:
          summary: "High Redis connection count"
          description: "Redis has {{ $value }} connected clients"

  - name: bdc-critical-alerts
    rules:
      # Service down alerts
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} has been down for more than 1 minute"

      # Very high error rate
      - alert: CriticalErrorRate
        expr: rate(flask_http_request_exceptions_total[5m]) > 0.5
        for: 1m
        labels:
          severity: critical
          service: bdc-backend
        annotations:
          summary: "Critical error rate detected on BDC backend"
          description: "Error rate is {{ $value }} errors per second"

      # Database down
      - alert: DatabaseDown
        expr: postgresql_up == 0
        for: 1m
        labels:
          severity: critical
          service: postgres
        annotations:
          summary: "PostgreSQL database is down"
          description: "PostgreSQL database has been unreachable for more than 1 minute"

      # Out of memory
      - alert: OutOfMemory
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.95
        for: 2m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "System is out of memory"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      # Disk full
      - alert: DiskFull
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) > 0.95
        for: 1m
        labels:
          severity: critical
          service: system
        annotations:
          summary: "Disk is almost full"
          description: "Disk usage is {{ $value | humanizePercentage }}"

  - name: bdc-performance-alerts
    rules:
      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      # High load average
      - alert: HighLoadAverage
        expr: node_load15 / count(count(node_cpu_seconds_total) by (cpu)) > 1.5
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High load average detected"
          description: "Load average is {{ $value }} on {{ $labels.instance }}"

      # Slow database queries
      - alert: SlowQueries
        expr: rate(postgresql_slow_queries_total[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
          service: postgres
        annotations:
          summary: "Slow database queries detected"
          description: "{{ $value }} slow queries per second detected"

  - name: bdc-business-alerts
    rules:
      # Low user activity
      - alert: LowUserActivity
        expr: rate(flask_http_requests_total{endpoint="/api/auth/login"}[1h]) < 0.001
        for: 30m
        labels:
          severity: info
          service: bdc-backend
        annotations:
          summary: "Low user login activity"
          description: "Login rate is {{ $value }} per second over the last hour"

      # High failed login attempts
      - alert: HighFailedLogins
        expr: rate(flask_http_requests_total{endpoint="/api/auth/login",status="401"}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
          service: bdc-backend
        annotations:
          summary: "High failed login attempts"
          description: "Failed login rate is {{ $value }} per second"