FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY client/package.json client/package-lock.json ./
RUN npm ci

# Expose port
EXPOSE 5173

# Start development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]