apiVersion: 1

datasources:
  # Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger
          urlDisplayLabel: "View trace"

  # Loki for logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    version: 1
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  # Jaeger for traces (if available)
  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger:16686
    version: 1
    editable: true

  # Node Exporter for system metrics
  - name: Node Exporter
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger

  # AlertManager
  - name: AlertManager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    version: 1
    editable: true
    jsonData:
      implementation: prometheus