# ================================
# Elasticsearch Configuration
# ================================

# --------------------------------
# Cluster Configuration
# --------------------------------
cluster.name: bdc-elk-cluster
node.name: ${HOSTNAME}
node.roles: [ master, data, ingest ]

# --------------------------------
# Network Configuration
# --------------------------------
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# --------------------------------
# Discovery Configuration
# --------------------------------
discovery.type: single-node
cluster.initial_master_nodes: ["${HOSTNAME}"]

# --------------------------------
# Memory Configuration
# --------------------------------
bootstrap.memory_lock: true
indices.memory.index_buffer_size: 20%

# --------------------------------
# Security Configuration
# --------------------------------
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# --------------------------------
# Monitoring Configuration
# --------------------------------
xpack.monitoring.collection.enabled: true

# --------------------------------
# Index Configuration
# --------------------------------
action.destructive_requires_name: true
cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%
cluster.routing.allocation.disk.watermark.flood_stage: 95%

# --------------------------------
# Performance Tuning
# --------------------------------
thread_pool:
  search:
    size: 5
    queue_size: 1000
  index:
    size: 2
    queue_size: 200

# Index settings
index:
  number_of_shards: 1
  number_of_replicas: 0
  refresh_interval: 30s

# --------------------------------
# Logging Configuration
# --------------------------------
logger:
  level: INFO
  org.elasticsearch.transport: DEBUG
  org.elasticsearch.discovery: DEBUG