apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdc-frontend
  namespace: bdc-production
  labels:
    app: bdc-frontend
    environment: production
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: bdc-frontend
  template:
    metadata:
      labels:
        app: bdc-frontend
        environment: production
    spec:
      containers:
      - name: bdc-frontend
        image: bdc-frontend:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        envFrom:
        - configMapRef:
            name: bdc-frontend-config
        - secretRef:
            name: bdc-frontend-secrets
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-logs
          mountPath: /var/log/nginx
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
      - name: nginx-logs
        emptyDir: {}
      securityContext:
        fsGroup: 101

---
apiVersion: v1
kind: Service
metadata:
  name: bdc-frontend-service
  namespace: bdc-production
  labels:
    app: bdc-frontend
    environment: production
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  selector:
    app: bdc-frontend

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bdc-frontend-hpa
  namespace: bdc-production
  labels:
    app: bdc-frontend
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bdc-frontend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80