apiVersion: v1
kind: Secret
metadata:
  name: bdc-backend-secrets
  namespace: bdc-production
  labels:
    app: bdc-backend
    environment: production
type: Opaque
stringData:
  # Database credentials
  POSTGRES_PASSWORD: "your-postgres-password-here"
  DATABASE_URL: "postgresql://bdc_user:your-postgres-password-here@postgres-service:5432/bdc_production"
  
  # Redis credentials
  REDIS_PASSWORD: "your-redis-password-here"
  REDIS_URL: "redis://:your-redis-password-here@redis-service:6379/0"
  
  # Application secrets
  SECRET_KEY: "your-flask-secret-key-here"
  JWT_SECRET_KEY: "your-jwt-secret-key-here"
  
  # Email configuration
  MAIL_SERVER: "your-smtp-server.com"
  MAIL_USERNAME: "your-email@domain.com"
  MAIL_PASSWORD: "your-email-password"
  
  # External services
  OPENAI_API_KEY: "your-openai-api-key"
  SENTRY_DSN: "your-sentry-dsn"
  NEW_RELIC_LICENSE_KEY: "your-newrelic-key"
  
  # AWS credentials
  AWS_ACCESS_KEY_ID: "your-aws-access-key"
  AWS_SECRET_ACCESS_KEY: "your-aws-secret-key"
  S3_BUCKET: "your-s3-bucket-name"

---
apiVersion: v1
kind: Secret
metadata:
  name: bdc-frontend-secrets
  namespace: bdc-production
  labels:
    app: bdc-frontend
    environment: production
type: Opaque
stringData:
  VITE_API_URL: "https://api.yourdomain.com"
  VITE_WS_URL: "wss://api.yourdomain.com"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: bdc-production
  labels:
    app: postgres
    environment: production
type: Opaque
stringData:
  POSTGRES_PASSWORD: "your-postgres-password-here"
  POSTGRES_USER: "bdc_user"
  POSTGRES_DB: "bdc_production"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: bdc-production
  labels:
    app: redis
    environment: production
type: Opaque
stringData:
  REDIS_PASSWORD: "your-redis-password-here"

---
# TLS Secret for HTTPS (replace with your actual certificates)
apiVersion: v1
kind: Secret
metadata:
  name: bdc-tls-secret
  namespace: bdc-production
  labels:
    app: bdc
    environment: production
type: kubernetes.io/tls
data:
  # Base64 encoded certificate and key
  # Replace these with your actual certificate data
  tls.crt: LS0tLS1CRUdJTi... # Your base64 encoded certificate
  tls.key: LS0tLS1CRUdJTi... # Your base64 encoded private key