"""Add notes column to beneficiaries

Revision ID: 523cfcc2b6e1
Revises: 18f88a9a739a
Create Date: 2025-05-16 03:41:26.625812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523cfcc2b6e1'
down_revision = '18f88a9a739a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beneficiaries', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
