# ================================
# Logstash Configuration
# ================================

# --------------------------------
# Node Configuration
# --------------------------------
node.name: bdc-logstash
path.data: /usr/share/logstash/data
path.config: /usr/share/logstash/pipeline
path.logs: /usr/share/logstash/logs

# --------------------------------
# Pipeline Configuration
# --------------------------------
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# --------------------------------
# API Configuration
# --------------------------------
http.host: "0.0.0.0"
http.port: 9600
api.enabled: true

# --------------------------------
# Monitoring Configuration
# --------------------------------
monitoring.enabled: true
monitoring.elasticsearch.hosts: ["http://elasticsearch:9200"]

# --------------------------------
# Performance Configuration
# --------------------------------
config.reload.automatic: true
config.reload.interval: 30s

# --------------------------------
# Queue Configuration
# --------------------------------
queue.type: memory
queue.max_bytes: 1gb

# --------------------------------
# Dead Letter Queue
# --------------------------------
dead_letter_queue.enable: true
dead_letter_queue.max_bytes: 1gb

# --------------------------------
# Logging Configuration
# --------------------------------
log.level: info
slowlog.threshold.warn: 2s
slowlog.threshold.info: 1s
slowlog.threshold.debug: 500ms
slowlog.threshold.trace: 100ms

# --------------------------------
# JVM Configuration
# --------------------------------
pipeline.java_execution: true
pipeline.plugin_classloaders: false